"""
Django settings for LXP project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from django.contrib.messages import constants as messages
import os
#from storages.backends.s3boto3 import S3Boto3Storage
import pymysql

pymysql.install_as_MySQLdb()
#class StaticStorage(S3Boto3Storage):
 #   location = 'static'  # ensures files are uploaded to static/ path
#STATICFILES_STORAGE = 'LXP.storage_backends.StaticStorage'
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR,'templates')
#STATIC_DIR=os.path.join(BASE_DIR,'https://lxp-static-s3.s3.us-east-1.amazonaws.comlxp-https://pub-20771ffbfa2343be8b01ca6bf4b7046c.r2.dev/lxp-static/')
#MEDIA_ROOT=os.path.join(BASE_DIR,'static')
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@k0#p3kidu)yaaa3u1hplxz)f@^6xiy384*(+n@@s5x#1bx@m5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['http://127.0.0.1/:8001','lxp.nubeera.com','*',
                 'https://lxp-django.onrender.com',"lxp-cdn-worker.mujahed-mca.workers.dev"]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lxpapp',
    'cto',
    'cfo',
    'trainer',
    'widget_tweaks',
    'social_django',        #add this
    'django.contrib.humanize',  # A set of Django template filters useful for adding a “human touch” to data.
    'django.contrib.sites',
    
]
INSTALLED_APPS += ["storages"]
#DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
#STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware', #add 
    'lxpapp.userlinktraking.RequestMiddleware',
    'lxpapp.userlinktraking.ErrorMiddleware',
    'lxpapp.userlinktraking.UserActivityMiddleware',
]
CSRF_COOKIE_SECURE=False
ROOT_URLCONF = 'LXP.urls'
CSRF_TRUSTED_ORIGINS = ['https://live.nubeera.com','https://*.nubeera.com',"https://lxp-django.onrender.com"]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',    #add 
            ],
        },
    },
]

WSGI_APPLICATION = 'LXP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
	    'default': {
	        'ENGINE': 'django.db.backends.mysql',
	        'NAME': 'lxp',
	        'USER': 'lxp',
	        'PASSWORD': 'Imranalikhan1973',
	        'HOST': '3.93.23.112',
	        'PORT': '3306',
	    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE =  'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True
DATE_FORMAT = "%d/%m/%Y"
DATE_INPUT_FORMATS = ['%d-%m-%Y', '%Y-%m-%d']
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
SITE_ID = 1
#STATIC_URL = 'lxp-https://pub-20771ffbfa2343be8b01ca6bf4b7046c.r2.dev/lxp-static/'
DEFAULT_AUTO_FIELD='django.db.models.AutoField' 
#STATICFILES_DIRS=[
#STATIC_DIR,
# ]

LOGIN_REDIRECT_URL='/userlogin'

#for contact us give your gmail id and password
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'apikey' # this email will be used to send emails
EMAIL_HOST_PASSWORD = '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' # host email password required
# now sign in with your host gmail account in your browser
# open following link and turn it ON
# https://myaccount.google.com/lesssecureapps
# otherwise you will get SMTPAuthenticationError at /contactus
# this process is required because google blocks apps authentication by default
EMAIL_RECEIVING_USER = ['info@nubeera.com'] # email on which you will receive messages sent from website

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'indexpage'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL = 'userlogin'
# # # ##########                  Dev
#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '709424261438-iq2t80mcempggouuh8t9os1afuhq2h3l.apps.googleusercontent.com'
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

#########                  Prod
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '699466001074-nja2mi4fl48gcb1l90lj9fq8mtamqvu2.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
   'https://www.googleapis.com/auth/userinfo.email',
   'https://www.googleapis.com/auth/userinfo.profile',
]
MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
}

JITSI_SECRET = "a5f9c73e4d85e0c9f25b2d4394b6d24d5c00f27aaebef34f97f13a9f6f1c9ec7"


# Add these settings to your settings.py file
GITHUB_TOKEN_ACTIVITY = '' #'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'
GITHUB_REPO_ACTIVITY = '' #'NubeEra-ImranAli/study_kit'
GITHUB_PATH_ACTIVITY = '' #'your_pdf_path_on_github'

MEET_BASE_URL = "https://meet.nubeera.com"
MEET_BASE_URL = "https://meet.nubeera.com"
#AWS_ACCESS_KEY_ID = 'AKIAXLJBIZM6LL5PRA7O'
#AWS_SECRET_ACCESS_KEY = 'QfKf9VJs9hCqUbq8+Nd8o7n/JFWIPdOpOSAYZMtd'
#AWS_STORAGE_BUCKET_NAME = 'lxp-static-s3'
#AWS_S3_CUSTOM_DOMAIN = f'lxp-static-s3.s3.us-east-1.amazonaws.com'
# Required for Cloudflare R2
CF_ACCESS_KEY_ID = os.getenv("CF_ACCESS_KEY_ID")
CF_SECRET_ACCESS_KEY = os.getenv("CF_SECRET_ACCESS_KEY")
CF_STORAGE_BUCKET_NAME = os.getenv("CF_BUCKET_NAME", "lxp-static")

CF_R2_ENDPOINT_URL = "https://11633c353da08a020c1ae70d3ecc106f.r2.cloudflarestorage.com"  # <-- Replace

CF_ACCESS_KEY_ID = 'cbfc61b53548bcf857c6189d9a7dbd49'
CF_SECRET_ACCESS_KEY = '203a93717073100e45c36fc1557ba53cb3d1f721e361aced1bae8972289e025b'
CF_STORAGE_BUCKET_NAME = 'lxp-static'
CF_CUSTOM_DOMAIN = f'https://pub-20771ffbfa2343be8b01ca6bf4b7046c.r2.dev'

#STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#STATIC_URL = f'https://lxp-static-s3.s3.us-east-1.amazonaws.comlxp-https://pub-20771ffbfa2343be8b01ca6bf4b7046c.r2.dev/lxp-static/'
#STATIC_URL = f'https://pub-20771ffbfa2343be8b01ca6bf4b7046c.r2.dev/lxp-static/'
STATIC_URL = "https://lxp-cdn-worker.mujahed-mca.workers.devlxp-https://pub-20771ffbfa2343be8b01ca6bf4b7046c.r2.dev/lxp-static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles") 

SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_SECURE = False     # Same here
