# Generated by Django 4.2.7 on 2025-06-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['playlist', 'video', 'serial_number']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='activityanswers',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='activityanswers',
            name='course',
        ),
        migrations.AddField(
            model_name='activity',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.playlist'),
        ),
        migrations.AddField(
            model_name='activity',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.video'),
        ),
    ]
