# Generated by Django 4.2.7 on 2025-01-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityanswers',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.chapter'),
        ),
    ]
