name: Upload index.html to Cloudflare R2

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Set up rclone config for R2
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          [r2]
          type = s3
          provider = Cloudflare
          env_auth = false
          access_key_id = ${{ secrets.RCLONE_R2_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.RCLONE_R2_SECRET_ACCESS_KEY }}
          endpoint = ${{ secrets.RCLONE_R2_ENDPOINT }}
          EOF
      - name: Show current directory and files
        run: |
          pwd
          ls -alh
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload index.html to R2 root
        run: |
          rclone copy index.html r2:migration-dn-proj/ \
            --s3-acl public-read \
            --no-update-modtime \
            --s3-no-head
      
